navbar:
  blog_title: 极地之旅
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    # - {
    #     key: "文档",
    #     icon: "iconfont icon-books",
    #     submenu:
    #       [
    #         { key: "主题博客", link: "https://hexo.fluid-dev.com/" },
    #         { key: "配置指南", link: "https://hexo.fluid-dev.com/docs/guide/" },
    #         { key: "图标用法", link: "https://hexo.fluid-dev.com/docs/icon/" },
    #       ],
    #   }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }


index:
  banner_img_height: 70
  banner_mask_alpha: 0.3
  banner_img: /img/bg/pexels-pixabay-531880.jpg
  slogan:
    enable: true
    text: Tech Trekker
    api:
      enable: true
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]


post:
  banner_img_height: 30
  banner_mask_alpha: 0.3
  banner_img: /img/bg/pexels-bri-schneiter-28802-346529.jpg
  meta:
    author:  # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
      enable: false
    date:  # 文章日期，优先根据 front-matter 里 date 字段，其次是 md 文件日期
      enable: true
      format: "dddd, MMMM Do YYYY, h:mm a"  # 格式参照 ISO-8601 日期格式化
    wordcount:  # 字数统计
      enable: true
      format: "{} 字"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read:  # 阅读时间
      enable: true
      format: "{} 分钟"
    views:  # 阅读次数
      enable: false
      source: "leancloud"  # 统计数据来源，可选：leancloud | busuanzi   注意不蒜子会间歇抽风
      format: "{} 次"
  code:
    copy_btn: true
    highlight:
      enable: true
      line_number: true
      lib: "highlightjs"
      highlightjs:
        style: 'Github Gist'
        bg_color: false
      prismjs:
        style: "default"
        preprocess: true
  comments:
    enable: true
    type: gitalk

gitalk:
  clientID: Ov23liQyP1i66dNFjbTS                           # 创建应用后的 Client id
  clientSecret: cdfb9ac08577bbe903a12997113afd1b5f1da43b   # 创建应用后的 Client secrets
  repo: 'geekeryy.github.io'                                 # 评论用的仓库名称
  owner: 'geekeryy'                                          # 填自己github账户名字就好
  admin: ['geekeryy']                                        # 填自己github账户名字就好
  language: zh-CN
  labels: ['Gitalk']
  perPage: 10
  pagerDirection: first
  distractionFreeMode: true
  createIssueManually: true
  proxy: 'https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token'
    
tag:
  banner_img_height: 70
  banner_mask_alpha: 0.3
  banner_img: /img/bg/pexels-pixabay-531880.jpg
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px  # 字号单位
    start_color: "#BBBBEE"
    end_color: "#337ab7"


archive:
  banner_img_height: 30
  banner_mask_alpha: 0.3
  banner_img: /img/bg/pexels-pixabay-531880.jpg


about:
  banner_img_height: 30
  banner_mask_alpha: 0.3
  banner_img: /img/bg/pexels-pixabay-531880.jpg
  avatar: /img/avatar.png
  name: "江杨"
  intro: "有些鸟儿是永远关不住的，因为他们的每一片羽翼都沾满了自由的光辉"
  icons:
      - { class: 'iconfont icon-github-fill', link: 'https://github.com/geekeryy', tip: 'GitHub' }
  

force_https: true

lazyload:
  enable: true
  loading_img: 
  onlypost: false
  offset_factor: 2



web_analytics:  # 网页访问统计
  enable: true # 默认为false，启用网页统计改为true即可
  baidu: d5b8abb66fa55af0cc5284ac456bf60e  # 百度统计的Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
  google:  # Google统计的Tracking ID，参见 https://analytics.google.com/analytics/web/
  tencent:  # 腾讯统计的H5 App id，参见 https://mta.qq.com/h5/manage/ctr_app_manage (开启高级功能才有cid)
    sid:
    cid:
  woyaola:  # 51.la站点统计ID，参见 https://www.51.la/user/site/index
  cnzz:  # 友盟/cnzz站点统计web_id，参见 https://web.umeng.com/main.php?c=site&a=show
  leancloud:  # LeanCloud 计数统计，可用于 PV UV 展示，如果 web_analytics.enable 没有开启，PV UV 展示只会查询，不会增加
    app_id:
    app_key:
    server_url:  # REST API 服务器地址，国际版不填